workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS Deployment Target
        script: |
          sed -i '' 's/platform :ios, '12.0'/platform :ios, '13.0'/' ios/Podfile
          cd ios
          pod install --repo-update
      - name: Build iOS App
        script: |
          flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa